package randoop.test;

/**
 * An {@code InvalidExceptionCheck} represents the occurrence of an exception tagged as an invalid
 * behavior during {@code Check} generation.
 */
@org.checkerframework.framework.qual.AnnotatedFor("org.checkerframework.checker.resourceleak.ResourceLeakChecker")
public class InvalidExceptionCheck extends ExceptionCheck {

    public InvalidExceptionCheck(@org.checkerframework.checker.calledmethods.qual.CalledMethods({}) Throwable exception,  @org.checkerframework.checker.calledmethods.qual.CalledMethods({}) int statementIndex, @org.checkerframework.checker.calledmethods.qual.CalledMethods({}) String catchClassName) {
        super(exception, statementIndex, catchClassName);
    }

    protected void appendCatchBehavior(@org.checkerframework.checker.calledmethods.qual.CalledMethods({ "toCodeStringPreStatement" }) InvalidExceptionCheck this, @org.checkerframework.checker.calledmethods.qual.CalledMethods({ "append" }) StringBuilder b) {
        b.append(String.format("// statement threw an invalid exception %s during test generation%n", exception.getClass().getName()));
    }

    @org.checkerframework.dataflow.qual.Pure
    protected void appendTryBehavior(@org.checkerframework.checker.calledmethods.qual.CalledMethods({ "toCodeStringPreStatement" }) InvalidExceptionCheck this, @org.checkerframework.checker.calledmethods.qual.CalledMethods({}) StringBuilder b) {
        // do nothing
    }
}
